<?php

use Illuminate\Database\Seeder;

class RestoransTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('restorans')->delete();
        
        \DB::table('restorans')->insert(array (
            0 => 
            array (
                'id' => '001',
                'nama' => 'Ayam Bakar Pawon',
                'no_telepon' => '',
                'lokasi' => 'Lantai 2',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 10:58:41',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r001.jpg',
            ),
            1 => 
            array (
                'id' => '002',
                'nama' => 'Ayam Goreng Fatmawati',
                'no_telepon' => '',
                'lokasi' => 'Lantai 2',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 10:58:51',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r002.jpg',
            ),
            2 => 
            array (
                'id' => '003',
                'nama' => 'Bakmi GM',
                'no_telepon' => '0215655007',
                'lokasi' => 'Lantai 2',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 10:58:59',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r003.jpg',
            ),
            3 => 
            array (
                'id' => '004',
                'nama' => 'Bakso Kota Cak Man',
                'no_telepon' => '',
                'lokasi' => 'Lantai 2',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 10:59:06',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r004.jpg',
            ),
            4 => 
            array (
                'id' => '005',
                'nama' => 'Bluenote Coffee',
                'no_telepon' => '',
                'lokasi' => 'Lantai 2',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 10:59:13',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r005.jpg',
            ),
            5 => 
            array (
                'id' => '006',
                'nama' => 'BreadTalk',
                'no_telepon' => '02178870892',
                'lokasi' => 'Lantai 2',
                'deskripsi' => '',
                'tax' => 0,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 10:59:18',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r006.jpg',
            ),
            6 => 
            array (
                'id' => '007',
            'nama' => 'CFC (California Fried Chicken)',
                'no_telepon' => '',
                'lokasi' => 'Lantai 2',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 10:59:26',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r007.jpg',
            ),
            7 => 
            array (
                'id' => '008',
                'nama' => 'Chatime',
                'no_telepon' => '',
                'lokasi' => 'Lantai 2',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 10:59:42',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r008.jpg',
            ),
            8 => 
            array (
                'id' => '009',
                'nama' => 'Clemmons',
                'no_telepon' => '',
                'lokasi' => 'Lantai 2',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 10:59:47',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r009.jpg',
            ),
            9 => 
            array (
                'id' => '010',
                'nama' => 'Dapur Iga',
                'no_telepon' => '08112144111',
                'lokasi' => 'Lantai 2',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:00:01',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r010.jpg',
            ),
            10 => 
            array (
                'id' => '011',
                'nama' => 'Tous Le Jours',
                'no_telepon' => '02129049256',
                'lokasi' => 'Lantai 1',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:00:10',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r011.jpg',
            ),
            11 => 
            array (
                'id' => '012',
                'nama' => 'Doner Kebab',
                'no_telepon' => '',
                'lokasi' => 'Lantai 2',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:00:15',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r012.jpg',
            ),
            12 => 
            array (
                'id' => '013',
                'nama' => 'Es Teler 77',
                'no_telepon' => '02178870877',
                'lokasi' => 'Lantai Paling Dasar',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:00:21',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r013.jpg',
            ),
            13 => 
            array (
                'id' => '014',
                'nama' => 'Fiesta Steak',
                'no_telepon' => '02178871062',
                'lokasi' => 'Lantai 1',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:00:26',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r014.jpg',
            ),
            14 => 
            array (
                'id' => '015',
                'nama' => 'Gula Merah',
                'no_telepon' => '',
                'lokasi' => 'Lantai Dasar',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:00:32',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r015.jpg',
            ),
            15 => 
            array (
                'id' => '016',
                'nama' => 'Hanamasa',
                'no_telepon' => '02178870911',
                'lokasi' => 'Lantai 1',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:00:39',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r016.jpg',
            ),
            16 => 
            array (
                'id' => '017',
                'nama' => 'Hoka Hoka Bento',
                'no_telepon' => '0211500505',
                'lokasi' => 'Lantai 2',
                'deskripsi' => 'ppl',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => 'hokahoka@bento.com',
                'created_at' => '2016-05-23 11:50:16',
                'updated_at' => '2016-05-23 04:50:16',
                'id_photo' => 'r017.jpg',
            ),
            17 => 
            array (
                'id' => '018',
                'nama' => 'Hop Hop',
                'no_telepon' => '',
                'lokasi' => 'Lantai 2',
                'deskripsi' => '',
                'tax' => 0,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:00:50',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r018.jpg',
            ),
            18 => 
            array (
                'id' => '019',
                'nama' => 'Ichiban Sushi',
                'no_telepon' => '02178870921',
                'lokasi' => 'Lantai Dasar',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:00:57',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r019.jpg',
            ),
            19 => 
            array (
                'id' => '020',
                'nama' => 'Ichiban Teppanyaki',
                'no_telepon' => '',
                'lokasi' => 'Lantai 2',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:01:02',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r020.jpg',
            ),
            20 => 
            array (
                'id' => '021',
                'nama' => 'Es Krim Uncle',
                'no_telepon' => '',
                'lokasi' => 'Lantai 2',
                'deskripsi' => '',
                'tax' => 0,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:01:11',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r021.jpg',
            ),
            21 => 
            array (
                'id' => '022',
                'nama' => 'Popcorn Stall',
                'no_telepon' => '',
                'lokasi' => 'Lantai 2',
                'deskripsi' => '',
                'tax' => 0,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:01:23',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r022.jpg',
            ),
            22 => 
            array (
                'id' => '023',
                'nama' => 'Wingstop',
                'no_telepon' => '0211500993',
                'lokasi' => 'Lantai 1',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:01:33',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r023.jpg',
            ),
            23 => 
            array (
                'id' => '024',
                'nama' => 'Imperial Cakery',
                'no_telepon' => '021 29049270',
                'lokasi' => 'Lantai Dasar',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:01:41',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r024.jpg',
            ),
            24 => 
            array (
                'id' => '025',
                'nama' => 'Imperial Kitchen',
                'no_telepon' => '02129049220',
                'lokasi' => 'Lantai 2',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:01:48',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r025.jpg',
            ),
            25 => 
            array (
                'id' => '026',
                'nama' => 'Itasuki',
                'no_telepon' => '02129049244',
                'lokasi' => 'Lantai 1',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:02:26',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r026.jpg',
            ),
            26 => 
            array (
                'id' => '027',
                'nama' => 'J.CO Donuts',
                'no_telepon' => '02178870998',
                'lokasi' => 'Lantai Dasar',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:02:36',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r027.jpg',
            ),
            27 => 
            array (
                'id' => '028',
                'nama' => 'Killiney Kopitiam',
                'no_telepon' => '02129049248',
                'lokasi' => 'Lantai Dasar',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:29:37',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => '',
            ),
            28 => 
            array (
                'id' => '029',
                'nama' => 'Lotteria',
                'no_telepon' => '02129049244',
                'lokasi' => 'Lantai 2',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:02:52',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r029.jpg',
            ),
            29 => 
            array (
                'id' => '030',
                'nama' => 'Marugame Udon & Tempura',
                'no_telepon' => '',
                'lokasi' => 'Lantai Dasar',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:02:59',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r030.jpg',
            ),
            30 => 
            array (
                'id' => '031',
                'nama' => 'MM Juice',
                'no_telepon' => '',
                'lokasi' => 'Lantai 2',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:03:05',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r031.jpg',
            ),
            31 => 
            array (
                'id' => '032',
                'nama' => 'Mujigae',
                'no_telepon' => '02129049202',
                'lokasi' => 'Lantai Dasar',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:03:10',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r032.jpg',
            ),
            32 => 
            array (
                'id' => '033',
                'nama' => 'Pecel Lele Lela',
                'no_telepon' => '02131713000',
                'lokasi' => 'Lantai 2',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:03:16',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r033.jpg',
            ),
            33 => 
            array (
                'id' => '034',
                'nama' => 'Nanny\'s Pavillon',
                'no_telepon' => '',
                'lokasi' => 'Lantai 1',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:03:23',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r034.jpg',
            ),
            34 => 
            array (
                'id' => '035',
                'nama' => 'O\'Crepes',
                'no_telepon' => '',
                'lokasi' => 'Lantai 2',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:03:29',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r035.jpg',
            ),
            35 => 
            array (
                'id' => '036',
                'nama' => 'Pawon Nyonya',
                'no_telepon' => '02178871085',
                'lokasi' => 'Lantai Paling Dasar',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:03:38',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r036.jpg',
            ),
            36 => 
            array (
                'id' => '037',
                'nama' => 'Pizza Hut',
                'no_telepon' => '02178884661',
                'lokasi' => 'Lantai Paling Dasar',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:03:57',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r037.jpg',
            ),
            37 => 
            array (
                'id' => '038',
                'nama' => 'Rainbow Express',
                'no_telepon' => '',
                'lokasi' => 'Lantai 2',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:30:29',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => '',
            ),
            38 => 
            array (
                'id' => '039',
                'nama' => 'Ramen 1',
                'no_telepon' => '',
                'lokasi' => 'Lantai 1',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:04:40',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r039.jpg',
            ),
            39 => 
            array (
                'id' => '040',
                'nama' => 'Rotiboy',
                'no_telepon' => '021788710999',
                'lokasi' => 'Lantai Paling Dasar',
                'deskripsi' => '',
                'tax' => 0,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:04:48',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r040.jpg',
            ),
            40 => 
            array (
                'id' => '041',
                'nama' => 'Yoshinoya',
                'no_telepon' => '021500566',
                'lokasi' => 'Lantai 2',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:05:36',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r041.jpg',
            ),
            41 => 
            array (
                'id' => '042',
                'nama' => 'Saboga',
                'no_telepon' => '',
                'lokasi' => 'Lantai 2',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:05:43',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r042.jpg',
            ),
            42 => 
            array (
                'id' => '043',
                'nama' => 'Sagoo Kitchen',
                'no_telepon' => '02176671067',
                'lokasi' => 'Lantai Dasar',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:05:53',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r043.jpg',
            ),
            43 => 
            array (
                'id' => '044',
                'nama' => 'Sosialita',
                'no_telepon' => '',
                'lokasi' => 'Lantai 1',
                'deskripsi' => '',
                'tax' => 15,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:06:03',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r044.jpg',
            ),
            44 => 
            array (
                'id' => '045',
                'nama' => 'Starbucks',
                'no_telepon' => '02178870894',
                'lokasi' => 'Lantai Dasar',
                'deskripsi' => '',
                'tax' => 0,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:06:24',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r045.jpg',
            ),
            45 => 
            array (
                'id' => '046',
                'nama' => 'Ta Wan',
                'no_telepon' => '02178870920',
                'lokasi' => 'Lantai Dasar',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:06:39',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r046.jpg',
            ),
            46 => 
            array (
                'id' => '047',
                'nama' => 'Shihlin Thailand Snack',
                'no_telepon' => '02129049265',
                'lokasi' => 'Lantai 2',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:06:47',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r047.jpg',
            ),
            47 => 
            array (
                'id' => '048',
                'nama' => 'Solaria',
                'no_telepon' => '02178870865',
                'lokasi' => 'Lantai 1',
                'deskripsi' => '',
                'tax' => 15,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:06:56',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r048.jpg',
            ),
            48 => 
            array (
                'id' => '049',
                'nama' => 'Soto Betawi Pancar',
                'no_telepon' => '',
                'lokasi' => 'Lantai 2',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:07:23',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r049.jpg',
            ),
            49 => 
            array (
                'id' => '050',
                'nama' => 'Tako and Sushi Box',
                'no_telepon' => '',
                'lokasi' => 'Lantai 2',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:07:29',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r050.jpg',
            ),
            50 => 
            array (
                'id' => '051',
                'nama' => 'Puyo',
                'no_telepon' => '02129704981',
                'lokasi' => 'Lantai 2',
                'deskripsi' => '',
                'tax' => 0,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:07:44',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r051.jpg',
            ),
            51 => 
            array (
                'id' => '052',
                'nama' => 'Shirokuma',
                'no_telepon' => '02129049284',
                'lokasi' => 'Lantai Dasar',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:07:51',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r052.jpg',
            ),
            52 => 
            array (
                'id' => '053',
                'nama' => 'BaskinRobbins',
                'no_telepon' => '',
                'lokasi' => 'Lantai Dasar',
                'deskripsi' => '',
                'tax' => 10,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:22:20',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => '',
            ),
            53 => 
            array (
                'id' => '054',
                'nama' => 'Mochi Mochi',
                'no_telepon' => '',
                'lokasi' => 'Lantai Dasar',
                'deskripsi' => '',
                'tax' => 0,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:30:06',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => '',
            ),
            54 => 
            array (
                'id' => '055',
                'nama' => 'Orchard Road Ice Cream',
                'no_telepon' => '',
                'lokasi' => 'Lantai Dasar',
                'deskripsi' => '',
                'tax' => 0,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:30:13',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => '',
            ),
            55 => 
            array (
                'id' => '056',
                'nama' => 'Marugame Udon',
                'no_telepon' => '',
                'lokasi' => 'Lantai Dasar',
                'deskripsi' => '',
                'tax' => 0,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:08:27',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r056.jpg',
            ),
            56 => 
            array (
                'id' => '057',
                'nama' => 'Sugar Cane',
                'no_telepon' => '',
                'lokasi' => 'Lantai 2',
                'deskripsi' => '',
                'tax' => 0,
                'rate' => '0.00',
                'admin' => '',
                'created_at' => '2016-05-23 11:08:33',
                'updated_at' => '0000-00-00 00:00:00',
                'id_photo' => 'r057.jpg',
            ),
        ));
        
        
    }
}
